# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='login_registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('wish_granted_at', models.DateField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('wish_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_creator', to='login_registration.User')),
                ('wish_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_granted', to='login_registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='wish_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_liked', to='belt.Wish'),
        ),
    ]
