# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wish_granted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_granted', to='login_registration.User'),
        ),
    ]
