# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_remove_user_date_of_birth'),
        ('belt', '0002_auto_20190625_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='login_registration.User'),
        ),
    ]
